### ISSUE TITLE
repo is corrupt

### ISSUE THREAD

**Issue by SimplebutComplex** [KJ7LNW/xnec2c#7]
Hi,
I tried to clone your repo and got

'''
$ git clone https://github.com/KJ7LNW/xnec2c.git
Cloning into 'xnec2c'...
remote: Enumerating objects: 2151, done.
remote: Counting objects: 100% (2151/2151), done.
remote: Compressing objects: 100% (740/740), done.
remote: Total 2151 (delta 1748), reused 1804 (delta 1403), pack-reused 0
Receiving objects: 100% (2151/2151), 2.77 MiB | 3.98 MiB/s, done.
Resolving deltas: 100% (1748/1748), done.
error: invalid path 'examples/2m_1:4l-gp_on_pole.nec'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
'''

**Comment by KJ7LNW** [comment]
Are you on Windows?   Looks like it failed because of the ":" in the name.

I just renamed example files with :'s in them and re-pushed, so delete the tree and try again.  You will be unable to checkout any commit prior to  HEAD in master unless you do some git magic like this from your local tree: https://stackoverflow.com/a/60767170/14055985 .

Depending on what you're up to you might want to look at the win32 branch here:
  https://github.com/KJ7LNW/xnec2c/tree/win32

xnec2c under Windows has a few issues to resolve.  Lets talk more if you're interested in picking up the task!

**Comment by KJ7LNW** [comment]
Hi @SimplebutComplex,

I'm closing this issue, but open a new one if you want to help with win32/64 dev.

Thanks!
